name: f_bapp
description: Chinchin Business App flutter 
publish_to: 'none'
version: 1.0.0+4

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  google_fonts: ^6.2.1
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.14
  package_info_plus: ^8.1.1
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  connectivity_plus: ^6.1.0
  another_flushbar: ^1.12.30
  shared_preferences: ^2.3.3
  local_auth: ^2.3.0
  local_auth_android: ^1.0.46
  flutter_spinkit: ^5.2.1
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_flavorizr: ^2.2.3
  talker_dio_logger: ^4.4.7

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/chinchin/
    - assets/images/
    - assets/modules/
  
