name: f_bapp
description: Chinchin Business App flutter 
publish_to: 'none'
version: 1.0.0+27

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  google_fonts: ^6.2.1
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.14
  package_info_plus: ^8.1.1
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  connectivity_plus: ^6.1.0
  another_flushbar: ^1.12.30
  shared_preferences: ^2.3.3
  local_auth: ^2.3.0
  flutter_spinkit: ^5.2.1
  dropdown_button2: ^2.3.9
  shimmer: ^3.0.0
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.3
  fl_chart: ^0.69.2
  intl: ^0.19.0
  currency_text_input_formatter: ^2.2.6
  money_formatter: ^0.0.6
  local_auth_android: ^1.0.46
  url_launcher: ^6.3.1
  pretty_qr_code: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_flavorizr: ^2.2.3
  talker_dio_logger: ^4.4.7

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/chinchin/
    - assets/modules/
    - assets/profile/
    - assets/modules/administration/
    - assets/modules/merchant/
    - assets/modules/onboarding/
    - assets/modules/operations/
    - lib/common/assets/images/social_media/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/chinchin/icono.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/chinchin/icono.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/chinchin/icono.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/chinchin/icono.png"
  
